name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20, 21, 22, 23]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - run: pnpm install
      - run: pnpm biome ci
      - run: pnpm test
      - run: pnpm build
      - run: pnpm test:coverage
        if: ${{ matrix.node == 23 }}
      - uses: codecov/codecov-action@v4
        if: ${{ matrix.node == 23 }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/clover.xml
          verbose: true
