name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20, 21, 22]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node }}
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm biome ci
      - run: pnpm test
      - run: pnpm build
      - run: pnpm test:coverage
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/clover.xml
          verbose: true
